# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file


# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "maven"
    directories: 
      - "/"
      - "/verifier-application"
      - "/verifier-service"
    groups:
      spring:
        patterns:
          - "org.springframework.*"
          - "org.springdoc*"
        update-types:
          - "patch"
          - "minor"
      swiyu:
        patterns:
          - "ch.admin.*"
          - "io.github.swiyu*"
      cryptography:
        patterns:
          - "org.bouncycastle*"
          - "com.nimbus*"
      database:
        patterns:
          - "org.flywaydb*"
          - "org.postgresql*"
          - "org.hibernate*"
          - "org.testcontainers*"
      monitoring:
        patterns:
          - "io.micrometer*"
          - "io.prometheus*"
      logging:
        patterns:
          - "ch.qos.logback*"
          - "net.logstash*"
      utility:
        patterns:
          - "org.projectlombok*"
          - "com.tngtech.archunit*"
          - "org.mock-server*"
          - "net.javacrumbs.shedlock*"
          - "net.java.dev.jna*" # For didresolver
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"