services:
  postgres:
    image: postgres:15.8
    environment:
      POSTGRES_USER: "verifier_mgmt_user"
      POSTGRES_PASSWORD: "secret"
      POSTGRES_DB: "verifier_db"
    ports:
      - '5434:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U verifier_mgmt_user -d verifier_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
