application:
  signing_key: "-----BEGIN EC PRIVATE KEY-----\nMHcCAQEEIGYpEuy/ijtVu+QOIsmXiK9HNPQ0bkBX+wvhaFAh/zoKoAoGCCqGSM49\nAwEHoUQDQgAEoqBwmYd3RAHs+sFe/U7UFTXbkWmPAaqKTHCvsV8tvxWeng+OkMo1\n8QOT2rDNk+qMBrCJnyyiRU6jMdH4q3z1Pg==\n-----END EC PRIVATE KEY-----\n"
  signing-key-verification-method: "did:example:12345#key-1"
  client-metadata-file: "classpath:client_metadata.json"
  client-id: "did:example:running-local"

spring:
  docker:
    compose:
      enabled: true
  mvc:
    log-resolved-exception: false # see https://stackoverflow.com/a/77147791
  jpa:
    hibernate:
      ddl-auto: create # when starting locally we connect to the db from compose.yml and generate the schema from hibernate
logging:
  level:
    ch.admin.bj.swiyu: DEBUG